/*
 * Copyright 2025 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define PCR_DSE_dse0 0x00u /*!<@brief Drive Strength Enable: Low */
#define PCR_IBE_ibe1 0x01u /*!<@brief Input Buffer Enable: Enables */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitFreeMASTER_UARTPins(void);

#define PCR_IBE_ibe1 0x01u          /*!<@brief Input Buffer Enable: Enables */
#define PCR_PE_pe1 0x01u            /*!<@brief Pull Enable: Enables */
#define PCR_PS_ps1 0x01u            /*!<@brief Pull Select: Enables internal pullup resistor */
#define PORT2_PCR25_MUX_mux00 0x00u /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */

/*! @name PORT3_29 (number 50), USER_LED
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDSPINS_USER_LED_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDSPINS_USER_LED_GPIO_PIN 29U              /*!<@brief GPIO pin number */
#define BOARD_INITLEDSPINS_USER_LED_GPIO_PIN_MASK (1U << 29U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITLEDSPINS_USER_LED_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLEDSPINS_USER_LED_PIN 29U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDSPINS_USER_LED_PIN_MASK (1U << 29U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT2_25 (number 44), LED_RED
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDSPINS_LED_RED_GPIO GPIO2                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_RED_GPIO_PIN 25U              /*!<@brief GPIO pin number */
#define BOARD_INITLEDSPINS_LED_RED_GPIO_PIN_MASK (1U << 25U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITLEDSPINS_LED_RED_PORT PORT2                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_RED_PIN 25U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDSPINS_LED_RED_PIN_MASK (1U << 25U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLEDsPins(void);

#define PCR_IBE_ibe1 0x01u         /*!<@brief Input Buffer Enable: Enables */
#define PORT4_PCR2_MUX_mux11 0x03u /*!<@brief Pin Multiplex Control: Alternative 3 (chip-specific) */
#define PORT4_PCR5_MUX_mux11 0x03u /*!<@brief Pin Multiplex Control: Alternative 3 (chip-specific) */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitUARTPins(void);

#define PCR_IBE_ibe1 0x01u /*!<@brief Input Buffer Enable: Enables */

/*! @name PORT3_0 (number 73), MC1_AT
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPWM0PINS_MC1_AT_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPWM0PINS_MC1_AT_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPWM0PINS_MC1_AT_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORT3_1 (number 72), MC1_AB
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPWM0PINS_MC1_AB_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPWM0PINS_MC1_AB_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPWM0PINS_MC1_AB_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORT3_8 (number 69), MC1_BT
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPWM0PINS_MC1_BT_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPWM0PINS_MC1_BT_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITPWM0PINS_MC1_BT_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORT3_9 (number 68), MC1_BB
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPWM0PINS_MC1_BB_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPWM0PINS_MC1_BB_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITPWM0PINS_MC1_BB_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORT3_10 (number 67), MC1_CT
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPWM0PINS_MC1_CT_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPWM0PINS_MC1_CT_PIN 10U                   /*!<@brief PORT pin number */
#define BOARD_INITPWM0PINS_MC1_CT_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORT3_11 (number 66), MC1_CB
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPWM0PINS_MC1_CB_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPWM0PINS_MC1_CB_PIN 11U                   /*!<@brief PORT pin number */
#define BOARD_INITPWM0PINS_MC1_CB_PIN_MASK (1U << 11U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORT3_6 (number 71), PFC_AT
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPWM0PINS_PFC_AT_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPWM0PINS_PFC_AT_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPWM0PINS_PFC_AT_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORT3_7 (number 70), PFC_BT
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPWM0PINS_PFC_BT_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPWM0PINS_PFC_BT_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITPWM0PINS_PFC_BT_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORT1_0 (number 91), FAULT_1
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPWM0PINS_FAULT_1_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPWM0PINS_FAULT_1_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPWM0PINS_FAULT_1_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORT1_1 (number 92), FAULT_2
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPWM0PINS_FAULT_2_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPWM0PINS_FAULT_2_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPWM0PINS_FAULT_2_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPWM0Pins(void);

#define PCR_IBE_ibe1 0x01u /*!<@brief Input Buffer Enable: Enables */

/*! @name PORT3_16 (number 59), MC2_AT
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPWM1PINS_MC2_AT_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPWM1PINS_MC2_AT_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_INITPWM1PINS_MC2_AT_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORT3_17 (number 58), MC2_AB
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPWM1PINS_MC2_AB_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPWM1PINS_MC2_AB_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_INITPWM1PINS_MC2_AB_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORT3_14 (number 61), MC2_BT
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPWM1PINS_MC2_BT_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPWM1PINS_MC2_BT_PIN 14U                   /*!<@brief PORT pin number */
#define BOARD_INITPWM1PINS_MC2_BT_PIN_MASK (1U << 14U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORT3_15 (number 60), MC2_BB
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPWM1PINS_MC2_BB_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPWM1PINS_MC2_BB_PIN 15U                   /*!<@brief PORT pin number */
#define BOARD_INITPWM1PINS_MC2_BB_PIN_MASK (1U << 15U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORT3_12 (number 63), MC2_CT
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPWM1PINS_MC2_CT_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPWM1PINS_MC2_CT_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_INITPWM1PINS_MC2_CT_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORT3_13 (number 62), MC2_CB
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPWM1PINS_MC2_CB_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPWM1PINS_MC2_CB_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_INITPWM1PINS_MC2_CB_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORT3_27 (number 52), MC3_AT
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPWM1PINS_MC3_AT_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPWM1PINS_MC3_AT_PIN 27U                   /*!<@brief PORT pin number */
#define BOARD_INITPWM1PINS_MC3_AT_PIN_MASK (1U << 27U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORT3_28 (number 51), MC3_AB
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPWM1PINS_MC3_AB_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPWM1PINS_MC3_AB_PIN 28U                   /*!<@brief PORT pin number */
#define BOARD_INITPWM1PINS_MC3_AB_PIN_MASK (1U << 28U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPWM1Pins(void);

#define PCR_IBE_ibe0 0x00u /*!<@brief Input Buffer Enable: Disables */

/*! @name PORT0_20 (number 87), MC1_I_phA
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITADC0PINS_MC1_I_phA_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITADC0PINS_MC1_I_phA_PIN 20U                   /*!<@brief PORT pin number */
#define BOARD_INITADC0PINS_MC1_I_phA_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORT0_21 (number 88), MC1_I_phB
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITADC0PINS_MC1_I_phB_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITADC0PINS_MC1_I_phB_PIN 21U                   /*!<@brief PORT pin number */
#define BOARD_INITADC0PINS_MC1_I_phB_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORT0_22 (number 89), MC1_I_phC
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITADC0PINS_MC1_I_phC_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITADC0PINS_MC1_I_phC_PIN 22U                   /*!<@brief PORT pin number */
#define BOARD_INITADC0PINS_MC1_I_phC_PIN_MASK (1U << 22U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORT0_23 (number 90), MC1_CUR_DCB
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITADC0PINS_MC1_CUR_DCB_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITADC0PINS_MC1_CUR_DCB_PIN 23U                   /*!<@brief PORT pin number */
#define BOARD_INITADC0PINS_MC1_CUR_DCB_PIN_MASK (1U << 23U)      /*!<@brief PORT pin mask */
                                                                 /* @} */

/*! @name PORT1_6 (number 99), MC1_Temp_IPM
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITADC0PINS_MC1_Temp_IPM_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITADC0PINS_MC1_Temp_IPM_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITADC0PINS_MC1_Temp_IPM_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                                 /* @} */

/*! @name PORT1_7 (number 100), MC1_TA
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITADC0PINS_MC1_TA_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITADC0PINS_MC1_TA_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITADC0PINS_MC1_TA_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORT0_18 (number 85), I_pfc1
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITADC0PINS_I_pfc1_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITADC0PINS_I_pfc1_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_INITADC0PINS_I_pfc1_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORT0_19 (number 86), I_pfc2
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITADC0PINS_I_pfc2_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITADC0PINS_I_pfc2_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_INITADC0PINS_I_pfc2_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORT1_5 (number 98), MC1_VOLT_DCB
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITADC0PINS_MC1_VOLT_DCB_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITADC0PINS_MC1_VOLT_DCB_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITADC0PINS_MC1_VOLT_DCB_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                                 /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitADC0Pins(void);

#define PCR_IBE_ibe0 0x00u         /*!<@brief Input Buffer Enable: Disables */
#define PORT2_PCR5_MUX_mux00 0x00u /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */

/*! @name PORT1_10 (number 3), MC2_I_phA
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITADC1PINS_MC2_I_phA_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITADC1PINS_MC2_I_phA_PIN 10U                   /*!<@brief PORT pin number */
#define BOARD_INITADC1PINS_MC2_I_phA_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORT1_11 (number 4), MC2_I_phB
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITADC1PINS_MC2_I_phB_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITADC1PINS_MC2_I_phB_PIN 11U                   /*!<@brief PORT pin number */
#define BOARD_INITADC1PINS_MC2_I_phB_PIN_MASK (1U << 11U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORT1_12 (number 5), MC2_I_phC
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITADC1PINS_MC2_I_phC_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITADC1PINS_MC2_I_phC_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_INITADC1PINS_MC2_I_phC_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORT1_14 (number 7), MC2_CUR_DCB
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITADC1PINS_MC2_CUR_DCB_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITADC1PINS_MC2_CUR_DCB_PIN 14U                   /*!<@brief PORT pin number */
#define BOARD_INITADC1PINS_MC2_CUR_DCB_PIN_MASK (1U << 14U)      /*!<@brief PORT pin mask */
                                                                 /* @} */

/*! @name PORT1_13 (number 6), MC2_VOLT_DCB
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITADC1PINS_MC2_VOLT_DCB_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITADC1PINS_MC2_VOLT_DCB_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_INITADC1PINS_MC2_VOLT_DCB_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                                  /* @} */

/*! @name PORT1_15 (number 8), MC3_I_phA
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITADC1PINS_MC3_I_phA_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITADC1PINS_MC3_I_phA_PIN 15U                   /*!<@brief PORT pin number */
#define BOARD_INITADC1PINS_MC3_I_phA_PIN_MASK (1U << 15U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORT2_1 (number 23), MC3_I_phB
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITADC1PINS_MC3_I_phB_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITADC1PINS_MC3_I_phB_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITADC1PINS_MC3_I_phB_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT2_5 (number 27), MC3_I_phC
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITADC1PINS_MC3_I_phC_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITADC1PINS_MC3_I_phC_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITADC1PINS_MC3_I_phC_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT3_30 (number 49), MC3_VOLT_DCB
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITADC1PINS_MC3_VOLT_DCB_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITADC1PINS_MC3_VOLT_DCB_PIN 30U                   /*!<@brief PORT pin number */
#define BOARD_INITADC1PINS_MC3_VOLT_DCB_PIN_MASK (1U << 30U)      /*!<@brief PORT pin mask */
                                                                  /* @} */

/*! @name PORT2_3 (number 25), MC3_CUR_DCB
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITADC1PINS_MC3_CUR_DCB_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITADC1PINS_MC3_CUR_DCB_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITADC1PINS_MC3_CUR_DCB_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                                /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitADC1Pins(void);

#define PCR_IBE_ibe1 0x01u          /*!<@brief Input Buffer Enable: Enables */
#define PORT2_PCR23_MUX_mux00 0x00u /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */
#define PORT2_PCR6_MUX_mux00 0x00u  /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */

/*! @name PORT2_23 (number 42), MCU_BRAKE
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITGPIOPINS_MCU_BRAKE_GPIO GPIO2                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITGPIOPINS_MCU_BRAKE_GPIO_PIN 23U              /*!<@brief GPIO pin number */
#define BOARD_INITGPIOPINS_MCU_BRAKE_GPIO_PIN_MASK (1U << 23U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITGPIOPINS_MCU_BRAKE_PORT PORT2                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITGPIOPINS_MCU_BRAKE_PIN 23U                   /*!<@brief PORT pin number */
#define BOARD_INITGPIOPINS_MCU_BRAKE_PIN_MASK (1U << 23U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORT3_18 (number 57), RLY_IN
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITGPIOPINS_RLY_IN_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITGPIOPINS_RLY_IN_GPIO_PIN 18U              /*!<@brief GPIO pin number */
#define BOARD_INITGPIOPINS_RLY_IN_GPIO_PIN_MASK (1U << 18U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITGPIOPINS_RLY_IN_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITGPIOPINS_RLY_IN_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_INITGPIOPINS_RLY_IN_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORT2_6 (number 28), MC3_CUR_DCB
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITGPIOPINS_MC3_CUR_DCB_GPIO GPIO2               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITGPIOPINS_MC3_CUR_DCB_GPIO_PIN 6U              /*!<@brief GPIO pin number */
#define BOARD_INITGPIOPINS_MC3_CUR_DCB_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITGPIOPINS_MC3_CUR_DCB_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITGPIOPINS_MC3_CUR_DCB_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITGPIOPINS_MC3_CUR_DCB_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                                /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitGPIOPins(void);

#define PCR_IBE_ibe0 0x00u /*!<@brief Input Buffer Enable: Disables */

/*! @name PORT1_4 (number 97), MC2_FAULT
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITCMP0PINS_MC2_FAULT_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITCMP0PINS_MC2_FAULT_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITCMP0PINS_MC2_FAULT_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT0_23 (number 90), MC1_CUR_DCB
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITCMP0PINS_MC1_CUR_DCB_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITCMP0PINS_MC1_CUR_DCB_PIN 23U                   /*!<@brief PORT pin number */
#define BOARD_INITCMP0PINS_MC1_CUR_DCB_PIN_MASK (1U << 23U)      /*!<@brief PORT pin mask */
                                                                 /* @} */

/*! @name PORT2_3 (number 25), MC3_CUR_DCB
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITCMP0PINS_MC3_CUR_DCB_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITCMP0PINS_MC3_CUR_DCB_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITCMP0PINS_MC3_CUR_DCB_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                                /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitCMP0Pins(void);

#define PCR_IBE_ibe0 0x00u /*!<@brief Input Buffer Enable: Disables */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitOPAMP0Pins(void);

#define PCR_IBE_ibe1 0x01u /*!<@brief Input Buffer Enable: Enables */

/*! @name PORT3_22 (number 53), MC3_BT
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_SMARTDMA0PINS_MC3_BT_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_SMARTDMA0PINS_MC3_BT_GPIO_PIN 21U              /*!<@brief GPIO pin number */
#define BOARD_SMARTDMA0PINS_MC3_BT_GPIO_PIN_MASK (1U << 21U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_SMARTDMA0PINS_MC3_BT_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_SMARTDMA0PINS_MC3_BT_PIN 21U                   /*!<@brief PORT pin number */
#define BOARD_SMARTDMA0PINS_MC3_BT_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORT3_21 (number 54), MC3_BB
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_SMARTDMA0PINS_MC3_BB_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_SMARTDMA0PINS_MC3_BB_GPIO_PIN 22U              /*!<@brief GPIO pin number */
#define BOARD_SMARTDMA0PINS_MC3_BB_GPIO_PIN_MASK (1U << 22U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_SMARTDMA0PINS_MC3_BB_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_SMARTDMA0PINS_MC3_BB_PIN 22U                   /*!<@brief PORT pin number */
#define BOARD_SMARTDMA0PINS_MC3_BB_PIN_MASK (1U << 22U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORT3_20 (number 55), MC3_CB
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_SMARTDMA0PINS_MC3_CB_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_SMARTDMA0PINS_MC3_CB_GPIO_PIN 20U              /*!<@brief GPIO pin number */
#define BOARD_SMARTDMA0PINS_MC3_CB_GPIO_PIN_MASK (1U << 20U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_SMARTDMA0PINS_MC3_CB_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_SMARTDMA0PINS_MC3_CB_PIN 20U                   /*!<@brief PORT pin number */
#define BOARD_SMARTDMA0PINS_MC3_CB_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORT3_19 (number 56), MC3_CT
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_SMARTDMA0PINS_MC3_CT_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_SMARTDMA0PINS_MC3_CT_GPIO_PIN 19U              /*!<@brief GPIO pin number */
#define BOARD_SMARTDMA0PINS_MC3_CT_GPIO_PIN_MASK (1U << 19U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_SMARTDMA0PINS_MC3_CT_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_SMARTDMA0PINS_MC3_CT_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_SMARTDMA0PINS_MC3_CT_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_SmartDMA0Pins(void);

#define PCR_IBE_ibe1 0x01u          /*!<@brief Input Buffer Enable: Enables */
#define PORT2_PCR20_MUX_mux01 0x01u /*!<@brief Pin Multiplex Control: Alternative 1 (chip-specific) */
#define PORT2_PCR21_MUX_mux01 0x01u /*!<@brief Pin Multiplex Control: Alternative 1 (chip-specific) */

/*! @name PORT2_20 (number 40), MC1_ENC_A
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_EQDC0PINS_MC1_ENC_A_PORT PORT2                /*!<@brief PORT peripheral base pointer */
#define BOARD_EQDC0PINS_MC1_ENC_A_PIN 20U                   /*!<@brief PORT pin number */
#define BOARD_EQDC0PINS_MC1_ENC_A_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORT2_21 (number 41), MC1_ENC_B
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_EQDC0PINS_MC1_ENC_B_PORT PORT2                /*!<@brief PORT peripheral base pointer */
#define BOARD_EQDC0PINS_MC1_ENC_B_PIN 21U                   /*!<@brief PORT pin number */
#define BOARD_EQDC0PINS_MC1_ENC_B_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORT3_31 (number 48), MC1_ENC_I
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_EQDC0PINS_MC1_ENC_I_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_EQDC0PINS_MC1_ENC_I_PIN 31U                   /*!<@brief PORT pin number */
#define BOARD_EQDC0PINS_MC1_ENC_I_PIN_MASK (1U << 31U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_eQDC0Pins(void);

#define PCR_IBE_ibe1 0x01u         /*!<@brief Input Buffer Enable: Enables */
#define PORT4_PCR6_MUX_mux01 0x01u /*!<@brief Pin Multiplex Control: Alternative 1 (chip-specific) */
#define PORT4_PCR7_MUX_mux01 0x01u /*!<@brief Pin Multiplex Control: Alternative 1 (chip-specific) */

/*! @name PORT4_6 (number 20), MC2_ENC_A
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_EQDC1PINS_MC2_ENC_A_PORT PORT4               /*!<@brief PORT peripheral base pointer */
#define BOARD_EQDC1PINS_MC2_ENC_A_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_EQDC1PINS_MC2_ENC_A_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORT4_7 (number 21), MC2_ENC_B
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_EQDC1PINS_MC2_ENC_B_PORT PORT4               /*!<@brief PORT peripheral base pointer */
#define BOARD_EQDC1PINS_MC2_ENC_B_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_EQDC1PINS_MC2_ENC_B_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_eQDC1Pins(void);

#define PCR_IBE_ibe0 0x00u          /*!<@brief Input Buffer Enable: Disables */
#define PORT2_PCR17_MUX_mux00 0x00u /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */
#define PORT2_PCR19_MUX_mux00 0x00u /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitOPAMP1Pins(void);

#define PCR_IBE_ibe0 0x00u         /*!<@brief Input Buffer Enable: Disables */
#define PORT2_PCR2_MUX_mux00 0x00u /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitDACPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
