/*
 * Copyright 2025 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v16.0
processor: MCXA166
package_id: MCXA166VLL
mcu_data: ksdk2_0
processor_version: 0.16.12
external_user_signals: {}
pin_labels:
- {pin_num: '71', pin_signal: P3_6/CLKOUT/LPSPI1_PCS3/LPUART3_RTS_B/CT4_MAT2/PWM0_A3/PWM1_A0/EZH_PIO6/FREQME_CLK_OUT1/ADC3_A12, label: PFC_AT, identifier: LED_GREEN;PFC_AT}
- {pin_num: '73', pin_signal: P3_0/WUU0_IN22/TRIG_IN0/LPUART3_RXD/CT_INP16/PWM0_A0/PWM1_X0/EZH_PIO0, label: MC1_AT, identifier: CompUH;Compressor_UH;MC1_AT}
- {pin_num: '69', pin_signal: P3_8/WUU0_IN23/TRIG_IN3/LPSPI1_SDO/LPUART1_RXD/CT_INP4/PWM0_A1/LPUART5_CTS_B/EZH_PIO8/CLKOUT, label: MC1_BT, identifier: Compressor_VH;MC1_BT}
- {pin_num: '67', pin_signal: P3_10/TRIG_IN5/LPSPI1_SCK/LPUART1_RTS_B/CT1_MAT0/PWM0_A2/LPUART5_TXD/EZH_PIO10, label: MC1_CT, identifier: Compressor_WH;MC1_CT}
- {pin_num: '72', pin_signal: P3_1/TRIG_IN1/LPUART3_TXD/CT_INP17/PWM0_B0/PWM1_X1/EZH_PIO1/FREQME_CLK_OUT0, label: MC1_AB, identifier: Compressor_UL;MC1_AB}
- {pin_num: '68', pin_signal: P3_9/TRIG_IN4/LPSPI1_SDI/LPUART1_TXD/CT_INP5/PWM0_B1/LPUART5_RTS_B/EZH_PIO9, label: MC1_BB, identifier: Compressor_VL;MC1_BB}
- {pin_num: '66', pin_signal: P3_11/WUU0_IN24/TRIG_IN6/LPSPI1_PCS0/LPUART1_CTS_B/CT1_MAT1/PWM0_B2/LPUART5_RXD/EZH_PIO11, label: MC1_CB, identifier: Compressor_WL;MC1_CB}
- {pin_num: '29', pin_signal: P2_7/TRIG_IN5/LPUART4_TXD/CT_INP19/CT1_MAT3/EZH_PIO31/VREFI/ADC1_A7/ADC3_A7/ADC0_A7/ADC2_A7, label: Compressor_FO, identifier: Compressor_FO}
- {pin_num: '49', pin_signal: P3_30/TRIG_OUT6/LPI2C3_SCLS/LPUART4_RTS_B/CT0_MAT2/PWM1_A0/EZH_PIO30/ADC1_A21, label: MC3_VOLT_DCB, identifier: Fan_UH;MC3_VOLT_DCB}
- {pin_num: '61', pin_signal: P3_14/WUU0_IN25/LPUART2_RXD/LPUART3_CTS_B/CT_INP6/PWM0_X2/PWM1_A1/EZH_PIO14/ADC3_A16, label: MC2_BT, identifier: Fan_VH;MC2_BT}
- {pin_num: '63', pin_signal: P3_12/LPUART2_RTS_B/LPUART3_TXD/CT1_MAT2/PWM0_X0/PWM1_A2/EZH_PIO12/ADC3_A14, label: MC2_CT, identifier: Fan_WH;MC2_CT}
- {pin_num: '62', pin_signal: P3_13/LPUART2_CTS_B/LPUART3_RXD/CT1_MAT3/PWM0_X1/PWM1_B2/EZH_PIO13/ADC3_A15, label: MC2_CB, identifier: Fan_WL;MC2_CB}
- {pin_num: '60', pin_signal: P3_15/LPUART2_TXD/LPUART3_RTS_B/CT_INP7/PWM0_X3/PWM1_B1/EZH_PIO15/ADC3_A17, label: MC2_BB, identifier: Fan_VL;MC2_BB}
- {pin_num: '48', pin_signal: P3_31/LPTMR0_ALT2/TRIG_IN10/LPI2C3_SDAS/LPUART4_CTS_B/CT0_MAT3/PWM1_B0/EZH_PIO31/ADC1_A20, label: MC1_ENC_I, identifier: Fan_UL;MC1_ENC_I}
- {pin_num: '52', pin_signal: P3_27/WUU0_IN30/TRIG_OUT7/LPI2C3_SCL/LPUART4_TXD/CT_INP13/CT3_MAT1/PWM1_A3/EZH_PIO27, label: MC3_AT, identifier: PFC_PWM;MC3_AT}
- {pin_num: '26', pin_signal: P2_4/LPUART2_CTS_B/CT_INP14/CT1_MAT0/EZH_PIO28/ADC0_A1/ADC2_A0/CMP2_IN0, label: ENV_TEMP, identifier: PFC_IDC;ENV_TEMP}
- {pin_num: '25', pin_signal: P2_3/WUU0_IN19/TRIG_IN7/LPUART0_CTS_B/LPUART2_RXD/CT_INP13/CT2_MAT3/EZH_PIO27/ADC0_A3/CMP1_IN0/ADC1_A4, label: MC3_CUR_DCB, identifier: MC3_CUR_DCB}
- {pin_num: '80', pin_signal: P0_6/ISPMODE_N/LPI2C0_HREQ/LPSPI0_PCS1/CT_INP2/EZH_PIO2/CMP1_OUT/CLKOUT/ADC0_A15, label: C_IPMT, identifier: C_IPMT}
- {pin_num: '100', pin_signal: P1_7/WUU0_IN9/TRIG_OUT2/LPUART2_CTS_B/CT_INP7/CT4_MAT1/EZH_PIO3/ADC0_A23, label: MC1_TA, identifier: EXH_TEMP;MC1_TA}
- {pin_num: '27', pin_signal: P2_5/LPUART2_RTS_B/CT_INP15/CT1_MAT1/EZH_PIO29/ADC1_A1/ADC3_A0, label: MC3_I_phC, identifier: F_IPMT;MC3_I_phC}
- {pin_num: '3', pin_signal: P1_10/LPUART1_RTS_B/LPI2C2_SDAS/CT2_MAT0/EZH_PIO6/LPUART5_TXD/CAN0_TXD/ADC1_A8, label: MC2_I_phA, identifier: UDCB;MC2_I_phA;MC1_Temp_IPM}
- {pin_num: '4', pin_signal: P1_11/WUU0_IN11/TRIG_OUT2/LPUART1_CTS_B/LPI2C2_SCLS/CT2_MAT1/EZH_PIO7/LPUART5_RXD/CAN0_RXD/ADC1_A9, label: MC2_I_phB, identifier: PFC_I;MC2_I_phB;MC1_TA}
- {pin_num: '5', pin_signal: P1_12/WUU0_IN12/LPI2C1_SDA/LPUART2_RXD/CT2_MAT2/EZH_PIO8/LPUART5_CTS_B/ADC1_A10, label: MC2_I_phC, identifier: VAC;MC2_I_phC}
- {pin_num: '6', pin_signal: P1_13/TRIG_IN3/LPI2C1_SCL/LPUART2_TXD/CT2_MAT3/EZH_PIO9/LPUART5_RTS_B/ADC1_A11, label: MC2_VOLT_DCB, identifier: RLY_IN;AA;RALAY;MCU_BRAKE;MC2_VOLT_DCB}
- {pin_num: '70', pin_signal: P3_7/TRIG_IN2/LPSPI1_PCS2/LPUART3_CTS_B/CT4_MAT3/PWM0_B3/PWM1_B0/EZH_PIO7/ADC3_A13, label: PFC_BT, identifier: wn4;WV4;PFC_BT}
- {pin_num: '10', pin_signal: P1_30/TRIG_OUT3/LPI2C0_SDA/CT_INP16/XTAL48M, label: EVALVE0, identifier: EVALVE0}
- {pin_num: '98', pin_signal: P1_5/FREQME_CLK_IN1/LPSPI0_PCS2/LPUART2_TXD/CT1_MAT3/EZH_PIO1/ADC0_A21/CMP1_IN2, label: MC1_VOLT_DCB, identifier: EVALVE1;MC1_VOLT_DCB}
- {pin_num: '99', pin_signal: P1_6/TRIG_IN2/LPSPI0_PCS1/LPUART2_RTS_B/CT_INP6/CT4_MAT0/EZH_PIO2/ADC0_A22, label: MC1_Temp_IPM, identifier: EVALVE2;MC1_Temp_IPM}
- {pin_num: '51', pin_signal: P3_28/WUU0_IN26/TRIG_IN11/LPI2C3_SDA/LPUART4_RXD/CT_INP12/CT3_MAT2/PWM1_B3/EZH_PIO28, label: MC3_AB, identifier: EVALVE3;MC3_AB}
- {pin_num: '97', pin_signal: P1_4/WUU0_IN8/FREQME_CLK_IN0/LPSPI0_PCS3/LPUART2_RXD/CT1_MAT2/EZH_PIO0/ADC0_A20/CMP0_IN2, label: MC2_FAULT, identifier: PFC_OC;MC1_VOLT_DCB;MC2_FAULT}
- {pin_num: '50', pin_signal: P3_29/WUU0_IN27/ISPMODE_N/LPI2C3_HREQ/CT_INP3/CT3_MAT3/EZH_PIO29/ADC1_A22, label: USER_LED, identifier: USER_LED}
- {pin_num: '44', pin_signal: P2_25/TRIG_OUT7/CT_INP9/ADC3_A3, label: LED_RED, identifier: LED_RED}
- {pin_num: '57', pin_signal: P3_18/LPUART4_RXD/CT2_MAT0/PWM0_X0/PWM1_X0/EZH_PIO18, label: RLY_IN, identifier: RALAY;RLY_IN}
- {pin_num: '42', pin_signal: P2_23/TRIG_OUT5/CT2_MAT3/ADC3_A2/OPAMP3_OUT, label: MCU_BRAKE, identifier: MCU_BRAKE}
- {pin_num: '87', pin_signal: P0_20/WUU0_IN4/LPUART0_RXD/CT_INP0/EZH_PIO10/CMP2_OUT/ADC0_A10, label: MC1_I_phA, identifier: I_phA;MC1_I_phA}
- {pin_num: '88', pin_signal: P0_21/LPUART0_TXD/CT_INP1/EZH_PIO11/ADC0_A11, label: MC1_I_phB, identifier: MC1_;MC1_I_phB}
- {pin_num: '89', pin_signal: P0_22/LPUART0_RTS_B/CT_INP2/CT0_MAT0/EZH_PIO12/ADC0_A12, label: MC1_I_phC, identifier: MC1_I_phC}
- {pin_num: '90', pin_signal: P0_23/WUU0_IN5/LPUART0_CTS_B/CT_INP3/CT0_MAT1/EZH_PIO13/ADC0_A13/CMP2_IN2, label: MC1_CUR_DCB, identifier: MC1_CUR_DCB}
- {pin_num: '7', pin_signal: P1_14/LPI2C1_SCLS/LPUART2_RTS_B/CT3_MAT0/EZH_PIO10/ADC1_A12, label: MC2_CUR_DCB, identifier: MC2_CUR_DCB}
- {pin_num: '8', pin_signal: P1_15/WUU0_IN13/LPI2C1_SDAS/LPUART2_CTS_B/CT3_MAT1/EZH_PIO11/ADC1_A13, label: MC3_I_phA, identifier: MC3_I_phB;MC3_I_phA}
- {pin_num: '23', pin_signal: P2_1/TRIG_IN7/LPUART0_TXD/LPUART4_RTS_B/CT_INP17/CT2_MAT1/EZH_PIO25/ADC1_A0/OPAMP2_INN, label: MC3_I_phB, identifier: MC3_I_phB}
- {pin_num: '91', pin_signal: P1_0/WUU0_IN6/LPTMR0_ALT3/TRIG_IN0/LPSPI0_SDO/LPI2C1_SDA/CT_INP4/CT0_MAT2/ADC0_A16/CMP0_IN3, label: FAULT_1, identifier: FAULT_1}
- {pin_num: '92', pin_signal: P1_1/TRIG_IN1/LPSPI0_SCK/LPI2C1_SCL/CT_INP5/CT0_MAT3/ADC0_A17/CMP1_IN3, label: FAULT_2, identifier: FAULT_2}
- {pin_num: '59', pin_signal: P3_16/LPUART4_RTS_B/CT_INP8/PWM1_A0/EZH_PIO16, label: MC2_AT, identifier: MC2_AT}
- {pin_num: '58', pin_signal: P3_17/LPUART4_CTS_B/CT_INP9/PWM1_B0/EZH_PIO17, label: MC2_AB, identifier: MC2_AB}
- {pin_num: '54', pin_signal: P3_21/TRIG_OUT1/LPI2C3_SCL/LPUART1_TXD/CT2_MAT3/PWM0_X3/PWM1_B3/EZH_PIO21/ADC3_A19, label: MC3_BB, identifier: MC3_BT;MC3_BB}
- {pin_num: '53', pin_signal: P3_22/LPUART1_RTS_B/CT_INP10/PWM1_X2/EZH_PIO22/ADC3_A20, label: MC3_BT, identifier: MC3_BB;MC3_BT}
- {pin_num: '56', pin_signal: P3_19/LPUART4_TXD/CT2_MAT1/PWM0_X1/PWM1_X1/EZH_PIO19, label: MC3_CT, identifier: MC3_CT}
- {pin_num: '55', pin_signal: P3_20/TRIG_OUT0/LPI2C3_SDA/LPUART1_RXD/CT2_MAT2/PWM0_X2/PWM1_A3/EZH_PIO20/ADC3_A18, label: MC3_CB, identifier: MC3_CB}
- {pin_num: '40', pin_signal: P2_20/TRIG_IN8/LPSPI1_PCS2/CT2_MAT0/EZH_PIO22/ADC2_A6/OPAMP3_INP, label: MC1_ENC_A, identifier: MC1_ENC_A}
- {pin_num: '41', pin_signal: P2_21/TRIG_IN9/LPSPI1_PCS3/CT2_MAT1/EZH_PIO23/ADC3_A6/OPAMP3_INN, label: MC1_ENC_B, identifier: MC1_ENC_B}
- {pin_num: '20', pin_signal: P4_6/TRIG_IN4/LPI2C2_HREQ/LPUART3_CTS_B/CT_INP6/PWM0_A0/EZH_PIO26/ADC2_A22, label: MC2_ENC_A, identifier: MC2_ENC_A}
- {pin_num: '21', pin_signal: P4_7/TRIG_IN5/LPUART3_RTS_B/CT_INP7/PWM0_B0/EZH_PIO27/ADC2_A23, label: MC2_ENC_B, identifier: MC2_ENC_B}
- {pin_num: '85', pin_signal: P0_18/LPI2C0_SCLS/CT0_MAT2/EZH_PIO8/CMP0_OUT/ADC0_A8, label: I_pfc1, identifier: I_pfc1}
- {pin_num: '86', pin_signal: P0_19/WUU0_IN3/LPI2C0_SDAS/CT0_MAT3/EZH_PIO9/CMP1_OUT/ADC0_A9, label: I_pfc2, identifier: I_pfc2}
- {pin_num: '28', pin_signal: P2_6/TRIG_OUT4/LPSPI1_PCS1/LPUART4_RXD/CT_INP18/CT1_MAT2/EZH_PIO30/ADC1_A3/ADC2_A2/OPAMP2_OUT, label: MC3_CUR_DCB, identifier: MC3_CUR_DCB}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "fsl_inputmux.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitFreeMASTER_UARTPins();
    BOARD_InitLEDsPins();
    BOARD_InitUARTPins();
    BOARD_InitPWM0Pins();
    BOARD_InitPWM1Pins();
    BOARD_InitADC0Pins();
    BOARD_InitADC1Pins();
    BOARD_InitGPIOPins();
    BOARD_InitCMP0Pins();
    BOARD_InitOPAMP0Pins();
    BOARD_SmartDMA0Pins();
    BOARD_eQDC0Pins();
    BOARD_eQDC1Pins();
    BOARD_InitOPAMP1Pins();
    BOARD_InitDACPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitFreeMASTER_UARTPins:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '79', peripheral: LPUART0, signal: TX, pin_signal: P0_3/TDI/LPUART0_TXD/LPSPI0_SDO/CT0_MAT1/UTICK_CAP1/CMP0_OUT/CMP1_IN1/ADC0_A14, drive_strength: low}
  - {pin_num: '78', peripheral: LPUART0, signal: RX, pin_signal: P0_2/TDO/SWO/LPUART0_RXD/LPSPI0_SCK/CT0_MAT0/UTICK_CAP0/ADC2_A8}
  - {peripheral: SmartDMA0, signal: 'TRIG, 0', pin_signal: cmp1_out}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitFreeMASTER_UARTPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitFreeMASTER_UARTPins(void)
{
    /* INPUTMUX0: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GateINPUTMUX0);
    /* PORT0: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT0);
    /* INPUTMUX0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kINPUTMUX0_RST_SHIFT_RSTn);
    /* LPUART0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kLPUART0_RST_SHIFT_RSTn);
    /* PORT0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT0_RST_SHIFT_RSTn);
    /*  Cmp1Out connect to Smartdma0Trigger 0 */
    INPUTMUX_AttachSignal(INPUTMUX0, 0U, kINPUTMUX_Cmp1OutToSmartdma0Trigger);

    /* PORT0_2 (pin 78) is configured as LPUART0_RXD */
    PORT_SetPinMux(PORT0, 2U, kPORT_MuxAlt2);

    PORT0->PCR[2] = ((PORT0->PCR[2] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT0_3 (pin 79) is configured as LPUART0_TXD */
    PORT_SetPinMux(PORT0, 3U, kPORT_MuxAlt2);

    PORT0->PCR[3] = ((PORT0->PCR[3] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_DSE_MASK | PORT_PCR_IBE_MASK)))

                     /* Drive Strength Enable: Low. */
                     | PORT_PCR_DSE(PCR_DSE_dse0)

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitLEDsPins:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '50', peripheral: GPIO3, signal: 'GPIO, 29', pin_signal: P3_29/WUU0_IN27/ISPMODE_N/LPI2C3_HREQ/CT_INP3/CT3_MAT3/EZH_PIO29/ADC1_A22, direction: OUTPUT}
  - {pin_num: '44', peripheral: GPIO2, signal: 'GPIO, 25', pin_signal: P2_25/TRIG_OUT7/CT_INP9/ADC3_A3, direction: OUTPUT, pull_select: up, pull_enable: enable}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitLEDsPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitLEDsPins(void)
{
    /* GPIO2: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GateGPIO2);
    /* GPIO3: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GateGPIO3);
    /* PORT2: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT2);
    /* PORT3: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT3);
    /* GPIO2 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kGPIO2_RST_SHIFT_RSTn);
    /* GPIO3 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kGPIO3_RST_SHIFT_RSTn);
    /* PORT2 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT2_RST_SHIFT_RSTn);
    /* PORT3 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT3_RST_SHIFT_RSTn);

    gpio_pin_config_t LED_RED_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO2_25 (pin 44)  */
    GPIO_PinInit(BOARD_INITLEDSPINS_LED_RED_GPIO, BOARD_INITLEDSPINS_LED_RED_PIN, &LED_RED_config);

    gpio_pin_config_t USER_LED_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO3_29 (pin 50)  */
    GPIO_PinInit(BOARD_INITLEDSPINS_USER_LED_GPIO, BOARD_INITLEDSPINS_USER_LED_PIN, &USER_LED_config);

    PORT2->PCR[25] = ((PORT2->PCR[25] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                      /* Pull Select: Enables internal pullup resistor. */
                      | PORT_PCR_PS(PCR_PS_ps1)

                      /* Pull Enable: Enables. */
                      | PORT_PCR_PE(PCR_PE_pe1)

                      /* Pin Multiplex Control: PORT2_25 (pin 44) is configured as P2_25. */
                      | PORT_PCR_MUX(PORT2_PCR25_MUX_mux00)

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_29 (pin 50) is configured as P3_29 */
    PORT_SetPinMux(BOARD_INITLEDSPINS_USER_LED_PORT, BOARD_INITLEDSPINS_USER_LED_PIN, kPORT_MuxAlt0);

    PORT3->PCR[29] = ((PORT3->PCR[29] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitUARTPins:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '19', peripheral: LPUART3, signal: TX, pin_signal: P4_5/TRIG_OUT3/LPI2C2_SCLS/LPUART3_TXD/CT4_MAT3/PWM0_B1/EZH_PIO25/ADC2_A21}
  - {pin_num: '16', peripheral: LPUART3, signal: RX, pin_signal: P4_2/WUU0_IN16/CLKOUT/LPI2C2_SDAS/LPUART3_RXD/CT4_MAT0/PWM0_A2/EZH_PIO22/ADC2_A18}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitUARTPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitUARTPins(void)
{
    /* PORT4: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT4);
    /* LPUART3 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kLPUART3_RST_SHIFT_RSTn);
    /* PORT4 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT4_RST_SHIFT_RSTn);

    PORT4->PCR[2] = ((PORT4->PCR[2] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                     /* Pin Multiplex Control: PORT4_2 (pin 16) is configured as LPUART3_RXD. */
                     | PORT_PCR_MUX(PORT4_PCR2_MUX_mux11)

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    PORT4->PCR[5] = ((PORT4->PCR[5] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                     /* Pin Multiplex Control: PORT4_5 (pin 19) is configured as LPUART3_TXD. */
                     | PORT_PCR_MUX(PORT4_PCR5_MUX_mux11)

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPWM0Pins:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '73', peripheral: FlexPWM0, signal: 'A, 0', pin_signal: P3_0/WUU0_IN22/TRIG_IN0/LPUART3_RXD/CT_INP16/PWM0_A0/PWM1_X0/EZH_PIO0, identifier: MC1_AT, direction: OUTPUT}
  - {pin_num: '72', peripheral: FlexPWM0, signal: 'B, 0', pin_signal: P3_1/TRIG_IN1/LPUART3_TXD/CT_INP17/PWM0_B0/PWM1_X1/EZH_PIO1/FREQME_CLK_OUT0, identifier: MC1_AB,
    direction: OUTPUT}
  - {pin_num: '69', peripheral: FlexPWM0, signal: 'A, 1', pin_signal: P3_8/WUU0_IN23/TRIG_IN3/LPSPI1_SDO/LPUART1_RXD/CT_INP4/PWM0_A1/LPUART5_CTS_B/EZH_PIO8/CLKOUT,
    identifier: MC1_BT, direction: OUTPUT}
  - {pin_num: '68', peripheral: FlexPWM0, signal: 'B, 1', pin_signal: P3_9/TRIG_IN4/LPSPI1_SDI/LPUART1_TXD/CT_INP5/PWM0_B1/LPUART5_RTS_B/EZH_PIO9, identifier: MC1_BB,
    direction: OUTPUT}
  - {pin_num: '67', peripheral: FlexPWM0, signal: 'A, 2', pin_signal: P3_10/TRIG_IN5/LPSPI1_SCK/LPUART1_RTS_B/CT1_MAT0/PWM0_A2/LPUART5_TXD/EZH_PIO10, identifier: MC1_CT,
    direction: OUTPUT}
  - {pin_num: '66', peripheral: FlexPWM0, signal: 'B, 2', pin_signal: P3_11/WUU0_IN24/TRIG_IN6/LPSPI1_PCS0/LPUART1_CTS_B/CT1_MAT1/PWM0_B2/LPUART5_RXD/EZH_PIO11, identifier: MC1_CB,
    direction: OUTPUT}
  - {pin_num: '71', peripheral: FlexPWM0, signal: 'A, 3', pin_signal: P3_6/CLKOUT/LPSPI1_PCS3/LPUART3_RTS_B/CT4_MAT2/PWM0_A3/PWM1_A0/EZH_PIO6/FREQME_CLK_OUT1/ADC3_A12,
    identifier: PFC_AT, direction: OUTPUT}
  - {pin_num: '70', peripheral: FlexPWM0, signal: 'B, 3', pin_signal: P3_7/TRIG_IN2/LPSPI1_PCS2/LPUART3_CTS_B/CT4_MAT3/PWM0_B3/PWM1_B0/EZH_PIO7/ADC3_A13, identifier: PFC_BT,
    direction: OUTPUT}
  - {pin_num: '91', peripheral: FlexPWM0, signal: 'PWM_FAULT_TRG_CH, 0', pin_signal: P1_0/WUU0_IN6/LPTMR0_ALT3/TRIG_IN0/LPSPI0_SDO/LPI2C1_SDA/CT_INP4/CT0_MAT2/ADC0_A16/CMP0_IN3}
  - {pin_num: '92', peripheral: FlexPWM0, signal: 'PWM_FAULT_TRG_CH, 1', pin_signal: P1_1/TRIG_IN1/LPSPI0_SCK/LPI2C1_SCL/CT_INP5/CT0_MAT3/ADC0_A17/CMP1_IN3}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPWM0Pins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPWM0Pins(void)
{
    /* INPUTMUX0: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GateINPUTMUX0);
    /* PORT1: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT1);
    /* PORT3: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT3);
    /* INPUTMUX0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kINPUTMUX0_RST_SHIFT_RSTn);
    /* FLEXPWM0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kFLEXPWM0_RST_SHIFT_RSTn);
    /* PORT1 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT1_RST_SHIFT_RSTn);
    /* PORT3 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT3_RST_SHIFT_RSTn);
    /*  TrigIn0 connect to FlexPwm0Fault 0 */
    INPUTMUX_AttachSignal(INPUTMUX0, 0U, kINPUTMUX_TrigIn0ToFlexPwm0Fault);
    /*  TrigIn1 connect to FlexPwm0Fault 1 */
    INPUTMUX_AttachSignal(INPUTMUX0, 1U, kINPUTMUX_TrigIn1ToFlexPwm0Fault);

    /* PORT1_0 (pin 91) is configured as TRIG_IN0 */
    PORT_SetPinMux(BOARD_INITPWM0PINS_FAULT_1_PORT, BOARD_INITPWM0PINS_FAULT_1_PIN, kPORT_MuxAlt1);

    PORT1->PCR[0] = ((PORT1->PCR[0] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT1_1 (pin 92) is configured as TRIG_IN1 */
    PORT_SetPinMux(BOARD_INITPWM0PINS_FAULT_2_PORT, BOARD_INITPWM0PINS_FAULT_2_PIN, kPORT_MuxAlt1);

    PORT1->PCR[1] = ((PORT1->PCR[1] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_0 (pin 73) is configured as PWM0_A0 */
    PORT_SetPinMux(BOARD_INITPWM0PINS_MC1_AT_PORT, BOARD_INITPWM0PINS_MC1_AT_PIN, kPORT_MuxAlt5);

    PORT3->PCR[0] = ((PORT3->PCR[0] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_1 (pin 72) is configured as PWM0_B0 */
    PORT_SetPinMux(BOARD_INITPWM0PINS_MC1_AB_PORT, BOARD_INITPWM0PINS_MC1_AB_PIN, kPORT_MuxAlt5);

    PORT3->PCR[1] = ((PORT3->PCR[1] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_10 (pin 67) is configured as PWM0_A2 */
    PORT_SetPinMux(BOARD_INITPWM0PINS_MC1_CT_PORT, BOARD_INITPWM0PINS_MC1_CT_PIN, kPORT_MuxAlt5);

    PORT3->PCR[10] = ((PORT3->PCR[10] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_11 (pin 66) is configured as PWM0_B2 */
    PORT_SetPinMux(BOARD_INITPWM0PINS_MC1_CB_PORT, BOARD_INITPWM0PINS_MC1_CB_PIN, kPORT_MuxAlt5);

    PORT3->PCR[11] = ((PORT3->PCR[11] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_6 (pin 71) is configured as PWM0_A3 */
    PORT_SetPinMux(BOARD_INITPWM0PINS_PFC_AT_PORT, BOARD_INITPWM0PINS_PFC_AT_PIN, kPORT_MuxAlt5);

    PORT3->PCR[6] = ((PORT3->PCR[6] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_7 (pin 70) is configured as PWM0_B3 */
    PORT_SetPinMux(BOARD_INITPWM0PINS_PFC_BT_PORT, BOARD_INITPWM0PINS_PFC_BT_PIN, kPORT_MuxAlt5);

    PORT3->PCR[7] = ((PORT3->PCR[7] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_8 (pin 69) is configured as PWM0_A1 */
    PORT_SetPinMux(BOARD_INITPWM0PINS_MC1_BT_PORT, BOARD_INITPWM0PINS_MC1_BT_PIN, kPORT_MuxAlt5);

    PORT3->PCR[8] = ((PORT3->PCR[8] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_9 (pin 68) is configured as PWM0_B1 */
    PORT_SetPinMux(BOARD_INITPWM0PINS_MC1_BB_PORT, BOARD_INITPWM0PINS_MC1_BB_PIN, kPORT_MuxAlt5);

    PORT3->PCR[9] = ((PORT3->PCR[9] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPWM1Pins:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '59', peripheral: FlexPWM1, signal: 'A, 0', pin_signal: P3_16/LPUART4_RTS_B/CT_INP8/PWM1_A0/EZH_PIO16, direction: OUTPUT}
  - {pin_num: '58', peripheral: FlexPWM1, signal: 'B, 0', pin_signal: P3_17/LPUART4_CTS_B/CT_INP9/PWM1_B0/EZH_PIO17, direction: OUTPUT}
  - {pin_num: '61', peripheral: FlexPWM1, signal: 'A, 1', pin_signal: P3_14/WUU0_IN25/LPUART2_RXD/LPUART3_CTS_B/CT_INP6/PWM0_X2/PWM1_A1/EZH_PIO14/ADC3_A16, identifier: MC2_BT,
    direction: OUTPUT}
  - {pin_num: '60', peripheral: FlexPWM1, signal: 'B, 1', pin_signal: P3_15/LPUART2_TXD/LPUART3_RTS_B/CT_INP7/PWM0_X3/PWM1_B1/EZH_PIO15/ADC3_A17, identifier: MC2_BB,
    direction: OUTPUT}
  - {pin_num: '63', peripheral: FlexPWM1, signal: 'A, 2', pin_signal: P3_12/LPUART2_RTS_B/LPUART3_TXD/CT1_MAT2/PWM0_X0/PWM1_A2/EZH_PIO12/ADC3_A14, identifier: MC2_CT,
    direction: OUTPUT}
  - {pin_num: '62', peripheral: FlexPWM1, signal: 'B, 2', pin_signal: P3_13/LPUART2_CTS_B/LPUART3_RXD/CT1_MAT3/PWM0_X1/PWM1_B2/EZH_PIO13/ADC3_A15, identifier: MC2_CB,
    direction: OUTPUT}
  - {pin_num: '52', peripheral: FlexPWM1, signal: 'A, 3', pin_signal: P3_27/WUU0_IN30/TRIG_OUT7/LPI2C3_SCL/LPUART4_TXD/CT_INP13/CT3_MAT1/PWM1_A3/EZH_PIO27, identifier: MC3_AT,
    direction: OUTPUT}
  - {pin_num: '51', peripheral: FlexPWM1, signal: 'B, 3', pin_signal: P3_28/WUU0_IN26/TRIG_IN11/LPI2C3_SDA/LPUART4_RXD/CT_INP12/CT3_MAT2/PWM1_B3/EZH_PIO28, identifier: MC3_AB,
    direction: OUTPUT}
  - {peripheral: FlexPWM1, signal: 'PWM_FAULT_TRG_CH, 0', pin_signal: cmp0_out}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPWM1Pins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPWM1Pins(void)
{
    /* INPUTMUX0: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GateINPUTMUX0);
    /* PORT3: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT3);
    /* INPUTMUX0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kINPUTMUX0_RST_SHIFT_RSTn);
    /* FLEXPWM1 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kFLEXPWM1_RST_SHIFT_RSTn);
    /* PORT3 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT3_RST_SHIFT_RSTn);
    /*  Cmp0Out connect to FlexPwm1Fault 0 */
    INPUTMUX_AttachSignal(INPUTMUX0, 0U, kINPUTMUX_Cmp0OutToFlexPwm1Fault);

    /* PORT3_12 (pin 63) is configured as PWM1_A2 */
    PORT_SetPinMux(BOARD_INITPWM1PINS_MC2_CT_PORT, BOARD_INITPWM1PINS_MC2_CT_PIN, kPORT_MuxAlt7);

    PORT3->PCR[12] = ((PORT3->PCR[12] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_13 (pin 62) is configured as PWM1_B2 */
    PORT_SetPinMux(BOARD_INITPWM1PINS_MC2_CB_PORT, BOARD_INITPWM1PINS_MC2_CB_PIN, kPORT_MuxAlt7);

    PORT3->PCR[13] = ((PORT3->PCR[13] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_14 (pin 61) is configured as PWM1_A1 */
    PORT_SetPinMux(BOARD_INITPWM1PINS_MC2_BT_PORT, BOARD_INITPWM1PINS_MC2_BT_PIN, kPORT_MuxAlt7);

    PORT3->PCR[14] = ((PORT3->PCR[14] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_15 (pin 60) is configured as PWM1_B1 */
    PORT_SetPinMux(BOARD_INITPWM1PINS_MC2_BB_PORT, BOARD_INITPWM1PINS_MC2_BB_PIN, kPORT_MuxAlt7);

    PORT3->PCR[15] = ((PORT3->PCR[15] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_16 (pin 59) is configured as PWM1_A0 */
    PORT_SetPinMux(BOARD_INITPWM1PINS_MC2_AT_PORT, BOARD_INITPWM1PINS_MC2_AT_PIN, kPORT_MuxAlt7);

    PORT3->PCR[16] = ((PORT3->PCR[16] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_17 (pin 58) is configured as PWM1_B0 */
    PORT_SetPinMux(BOARD_INITPWM1PINS_MC2_AB_PORT, BOARD_INITPWM1PINS_MC2_AB_PIN, kPORT_MuxAlt7);

    PORT3->PCR[17] = ((PORT3->PCR[17] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_27 (pin 52) is configured as PWM1_A3 */
    PORT_SetPinMux(BOARD_INITPWM1PINS_MC3_AT_PORT, BOARD_INITPWM1PINS_MC3_AT_PIN, kPORT_MuxAlt7);

    PORT3->PCR[27] = ((PORT3->PCR[27] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_28 (pin 51) is configured as PWM1_B3 */
    PORT_SetPinMux(BOARD_INITPWM1PINS_MC3_AB_PORT, BOARD_INITPWM1PINS_MC3_AB_PIN, kPORT_MuxAlt7);

    PORT3->PCR[28] = ((PORT3->PCR[28] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitADC0Pins:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '87', peripheral: ADC0, signal: 'A, 10', pin_signal: P0_20/WUU0_IN4/LPUART0_RXD/CT_INP0/EZH_PIO10/CMP2_OUT/ADC0_A10, identifier: MC1_I_phA}
  - {pin_num: '88', peripheral: ADC0, signal: 'A, 11', pin_signal: P0_21/LPUART0_TXD/CT_INP1/EZH_PIO11/ADC0_A11, identifier: MC1_I_phB}
  - {pin_num: '89', peripheral: ADC0, signal: 'A, 12', pin_signal: P0_22/LPUART0_RTS_B/CT_INP2/CT0_MAT0/EZH_PIO12/ADC0_A12}
  - {pin_num: '90', peripheral: ADC0, signal: 'A, 13', pin_signal: P0_23/WUU0_IN5/LPUART0_CTS_B/CT_INP3/CT0_MAT1/EZH_PIO13/ADC0_A13/CMP2_IN2}
  - {pin_num: '99', peripheral: ADC0, signal: 'A, 22', pin_signal: P1_6/TRIG_IN2/LPSPI0_PCS1/LPUART2_RTS_B/CT_INP6/CT4_MAT0/EZH_PIO2/ADC0_A22, identifier: MC1_Temp_IPM}
  - {pin_num: '100', peripheral: ADC0, signal: 'A, 23', pin_signal: P1_7/WUU0_IN9/TRIG_OUT2/LPUART2_CTS_B/CT_INP7/CT4_MAT1/EZH_PIO3/ADC0_A23, identifier: MC1_TA}
  - {pin_num: '85', peripheral: ADC0, signal: 'A, 8', pin_signal: P0_18/LPI2C0_SCLS/CT0_MAT2/EZH_PIO8/CMP0_OUT/ADC0_A8}
  - {pin_num: '86', peripheral: ADC0, signal: 'A, 9', pin_signal: P0_19/WUU0_IN3/LPI2C0_SDAS/CT0_MAT3/EZH_PIO9/CMP1_OUT/ADC0_A9}
  - {pin_num: '98', peripheral: ADC0, signal: 'A, 21', pin_signal: P1_5/FREQME_CLK_IN1/LPSPI0_PCS2/LPUART2_TXD/CT1_MAT3/EZH_PIO1/ADC0_A21/CMP1_IN2, identifier: MC1_VOLT_DCB}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitADC0Pins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitADC0Pins(void)
{
    /* PORT0: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT0);
    /* PORT1: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT1);
    /* ADC0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kADC0_RST_SHIFT_RSTn);
    /* PORT0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT0_RST_SHIFT_RSTn);
    /* CMP2 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kCMP2_RST_SHIFT_RSTn);
    /* PORT1 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT1_RST_SHIFT_RSTn);

    /* PORT0_18 (pin 85) is configured as ADC0_A8 */
    PORT_SetPinMux(BOARD_INITADC0PINS_I_pfc1_PORT, BOARD_INITADC0PINS_I_pfc1_PIN, kPORT_MuxAlt0);

    PORT0->PCR[18] = ((PORT0->PCR[18] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Disables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe0));

    /* PORT0_19 (pin 86) is configured as ADC0_A9 */
    PORT_SetPinMux(BOARD_INITADC0PINS_I_pfc2_PORT, BOARD_INITADC0PINS_I_pfc2_PIN, kPORT_MuxAlt0);

    PORT0->PCR[19] = ((PORT0->PCR[19] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Disables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe0));

    /* PORT0_20 (pin 87) is configured as ADC0_A10 */
    PORT_SetPinMux(BOARD_INITADC0PINS_MC1_I_phA_PORT, BOARD_INITADC0PINS_MC1_I_phA_PIN, kPORT_MuxAlt0);

    PORT0->PCR[20] = ((PORT0->PCR[20] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Disables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe0));

    /* PORT0_21 (pin 88) is configured as ADC0_A11 */
    PORT_SetPinMux(BOARD_INITADC0PINS_MC1_I_phB_PORT, BOARD_INITADC0PINS_MC1_I_phB_PIN, kPORT_MuxAlt0);

    PORT0->PCR[21] = ((PORT0->PCR[21] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Disables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe0));

    /* PORT0_22 (pin 89) is configured as ADC0_A12 */
    PORT_SetPinMux(BOARD_INITADC0PINS_MC1_I_phC_PORT, BOARD_INITADC0PINS_MC1_I_phC_PIN, kPORT_MuxAlt0);

    PORT0->PCR[22] = ((PORT0->PCR[22] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Disables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe0));

    /* PORT0_23 (pin 90) is configured as ADC0_A13 */
    PORT_SetPinMux(BOARD_INITADC0PINS_MC1_CUR_DCB_PORT, BOARD_INITADC0PINS_MC1_CUR_DCB_PIN, kPORT_MuxAlt0);

    PORT0->PCR[23] = ((PORT0->PCR[23] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Disables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe0));

    /* PORT1_5 (pin 98) is configured as ADC0_A21 */
    PORT_SetPinMux(BOARD_INITADC0PINS_MC1_VOLT_DCB_PORT, BOARD_INITADC0PINS_MC1_VOLT_DCB_PIN, kPORT_MuxAlt0);

    PORT1->PCR[5] = ((PORT1->PCR[5] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Disables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe0));

    /* PORT1_6 (pin 99) is configured as ADC0_A22 */
    PORT_SetPinMux(BOARD_INITADC0PINS_MC1_Temp_IPM_PORT, BOARD_INITADC0PINS_MC1_Temp_IPM_PIN, kPORT_MuxAlt0);

    PORT1->PCR[6] = ((PORT1->PCR[6] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Disables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe0));

    /* PORT1_7 (pin 100) is configured as ADC0_A23 */
    PORT_SetPinMux(BOARD_INITADC0PINS_MC1_TA_PORT, BOARD_INITADC0PINS_MC1_TA_PIN, kPORT_MuxAlt0);

    PORT1->PCR[7] = ((PORT1->PCR[7] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Disables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe0));
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitADC1Pins:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '3', peripheral: ADC1, signal: 'A, 8', pin_signal: P1_10/LPUART1_RTS_B/LPI2C2_SDAS/CT2_MAT0/EZH_PIO6/LPUART5_TXD/CAN0_TXD/ADC1_A8, identifier: MC2_I_phA}
  - {pin_num: '4', peripheral: ADC1, signal: 'A, 9', pin_signal: P1_11/WUU0_IN11/TRIG_OUT2/LPUART1_CTS_B/LPI2C2_SCLS/CT2_MAT1/EZH_PIO7/LPUART5_RXD/CAN0_RXD/ADC1_A9,
    identifier: MC2_I_phB}
  - {pin_num: '5', peripheral: ADC1, signal: 'A, 10', pin_signal: P1_12/WUU0_IN12/LPI2C1_SDA/LPUART2_RXD/CT2_MAT2/EZH_PIO8/LPUART5_CTS_B/ADC1_A10, identifier: MC2_I_phC}
  - {pin_num: '7', peripheral: ADC1, signal: 'A, 12', pin_signal: P1_14/LPI2C1_SCLS/LPUART2_RTS_B/CT3_MAT0/EZH_PIO10/ADC1_A12}
  - {pin_num: '6', peripheral: ADC1, signal: 'A, 11', pin_signal: P1_13/TRIG_IN3/LPI2C1_SCL/LPUART2_TXD/CT2_MAT3/EZH_PIO9/LPUART5_RTS_B/ADC1_A11, identifier: MC2_VOLT_DCB}
  - {pin_num: '8', peripheral: ADC1, signal: 'A, 13', pin_signal: P1_15/WUU0_IN13/LPI2C1_SDAS/LPUART2_CTS_B/CT3_MAT1/EZH_PIO11/ADC1_A13, identifier: MC3_I_phA}
  - {pin_num: '23', peripheral: ADC1, signal: 'A, 0', pin_signal: P2_1/TRIG_IN7/LPUART0_TXD/LPUART4_RTS_B/CT_INP17/CT2_MAT1/EZH_PIO25/ADC1_A0/OPAMP2_INN}
  - {pin_num: '27', peripheral: ADC1, signal: 'A, 1', pin_signal: P2_5/LPUART2_RTS_B/CT_INP15/CT1_MAT1/EZH_PIO29/ADC1_A1/ADC3_A0, identifier: MC3_I_phC}
  - {pin_num: '49', peripheral: ADC1, signal: 'A, 21', pin_signal: P3_30/TRIG_OUT6/LPI2C3_SCLS/LPUART4_RTS_B/CT0_MAT2/PWM1_A0/EZH_PIO30/ADC1_A21, identifier: MC3_VOLT_DCB}
  - {pin_num: '25', peripheral: ADC1, signal: 'A, 4', pin_signal: P2_3/WUU0_IN19/TRIG_IN7/LPUART0_CTS_B/LPUART2_RXD/CT_INP13/CT2_MAT3/EZH_PIO27/ADC0_A3/CMP1_IN0/ADC1_A4}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitADC1Pins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitADC1Pins(void)
{
    /* PORT1: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT1);
    /* PORT2: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT2);
    /* PORT3: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT3);
    /* ADC1 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kADC1_RST_SHIFT_RSTn);
    /* PORT1 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT1_RST_SHIFT_RSTn);
    /* PORT2 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT2_RST_SHIFT_RSTn);
    /* CMP1 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kCMP1_RST_SHIFT_RSTn);
    /* PORT3 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT3_RST_SHIFT_RSTn);

    /* PORT1_10 (pin 3) is configured as ADC1_A8 */
    PORT_SetPinMux(BOARD_INITADC1PINS_MC2_I_phA_PORT, BOARD_INITADC1PINS_MC2_I_phA_PIN, kPORT_MuxAlt0);

    PORT1->PCR[10] = ((PORT1->PCR[10] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Disables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe0));

    /* PORT1_11 (pin 4) is configured as ADC1_A9 */
    PORT_SetPinMux(BOARD_INITADC1PINS_MC2_I_phB_PORT, BOARD_INITADC1PINS_MC2_I_phB_PIN, kPORT_MuxAlt0);

    PORT1->PCR[11] = ((PORT1->PCR[11] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Disables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe0));

    /* PORT1_12 (pin 5) is configured as ADC1_A10 */
    PORT_SetPinMux(BOARD_INITADC1PINS_MC2_I_phC_PORT, BOARD_INITADC1PINS_MC2_I_phC_PIN, kPORT_MuxAlt0);

    PORT1->PCR[12] = ((PORT1->PCR[12] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Disables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe0));

    /* PORT1_13 (pin 6) is configured as ADC1_A11 */
    PORT_SetPinMux(BOARD_INITADC1PINS_MC2_VOLT_DCB_PORT, BOARD_INITADC1PINS_MC2_VOLT_DCB_PIN, kPORT_MuxAlt0);

    PORT1->PCR[13] = ((PORT1->PCR[13] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Disables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe0));

    /* PORT1_14 (pin 7) is configured as ADC1_A12 */
    PORT_SetPinMux(BOARD_INITADC1PINS_MC2_CUR_DCB_PORT, BOARD_INITADC1PINS_MC2_CUR_DCB_PIN, kPORT_MuxAlt0);

    PORT1->PCR[14] = ((PORT1->PCR[14] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Disables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe0));

    /* PORT1_15 (pin 8) is configured as ADC1_A13 */
    PORT_SetPinMux(BOARD_INITADC1PINS_MC3_I_phA_PORT, BOARD_INITADC1PINS_MC3_I_phA_PIN, kPORT_MuxAlt0);

    PORT1->PCR[15] = ((PORT1->PCR[15] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Disables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe0));

    /* PORT2_1 (pin 23) is configured as ADC1_A0 */
    PORT_SetPinMux(BOARD_INITADC1PINS_MC3_I_phB_PORT, BOARD_INITADC1PINS_MC3_I_phB_PIN, kPORT_MuxAlt0);

    PORT2->PCR[1] = ((PORT2->PCR[1] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Disables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe0));

    /* PORT2_3 (pin 25) is configured as ADC1_A4 */
    PORT_SetPinMux(BOARD_INITADC1PINS_MC3_CUR_DCB_PORT, BOARD_INITADC1PINS_MC3_CUR_DCB_PIN, kPORT_MuxAlt0);

    PORT2->PCR[3] = ((PORT2->PCR[3] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Disables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe0));

    PORT2->PCR[5] = ((PORT2->PCR[5] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                     /* Pin Multiplex Control: PORT2_5 (pin 27) is configured as ADC1_A1. */
                     | PORT_PCR_MUX(PORT2_PCR5_MUX_mux00)

                     /* Input Buffer Enable: Disables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe0));

    /* PORT3_30 (pin 49) is configured as ADC1_A21 */
    PORT_SetPinMux(BOARD_INITADC1PINS_MC3_VOLT_DCB_PORT, BOARD_INITADC1PINS_MC3_VOLT_DCB_PIN, kPORT_MuxAlt0);

    PORT3->PCR[30] = ((PORT3->PCR[30] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Disables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe0));
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitGPIOPins:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '42', peripheral: GPIO2, signal: 'GPIO, 23', pin_signal: P2_23/TRIG_OUT5/CT2_MAT3/ADC3_A2/OPAMP3_OUT, direction: OUTPUT}
  - {pin_num: '57', peripheral: GPIO3, signal: 'GPIO, 18', pin_signal: P3_18/LPUART4_RXD/CT2_MAT0/PWM0_X0/PWM1_X0/EZH_PIO18, identifier: RLY_IN, direction: OUTPUT}
  - {pin_num: '28', peripheral: GPIO2, signal: 'GPIO, 6', pin_signal: P2_6/TRIG_OUT4/LPSPI1_PCS1/LPUART4_RXD/CT_INP18/CT1_MAT2/EZH_PIO30/ADC1_A3/ADC2_A2/OPAMP2_OUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitGPIOPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitGPIOPins(void)
{
    /* GPIO2: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GateGPIO2);
    /* GPIO3: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GateGPIO3);
    /* PORT2: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT2);
    /* PORT3: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT3);
    /* GPIO2 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kGPIO2_RST_SHIFT_RSTn);
    /* GPIO3 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kGPIO3_RST_SHIFT_RSTn);
    /* PORT2 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT2_RST_SHIFT_RSTn);
    /* PORT3 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT3_RST_SHIFT_RSTn);

    gpio_pin_config_t MCU_BRAKE_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO2_23 (pin 42)  */
    GPIO_PinInit(BOARD_INITGPIOPINS_MCU_BRAKE_GPIO, BOARD_INITGPIOPINS_MCU_BRAKE_PIN, &MCU_BRAKE_config);

    gpio_pin_config_t RLY_IN_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO3_18 (pin 57)  */
    GPIO_PinInit(BOARD_INITGPIOPINS_RLY_IN_GPIO, BOARD_INITGPIOPINS_RLY_IN_PIN, &RLY_IN_config);

    PORT2->PCR[23] = ((PORT2->PCR[23] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                      /* Pin Multiplex Control: PORT2_23 (pin 42) is configured as P2_23. */
                      | PORT_PCR_MUX(PORT2_PCR23_MUX_mux00)

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    PORT2->PCR[6] = ((PORT2->PCR[6] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                     /* Pin Multiplex Control: PORT2_6 (pin 28) is configured as P2_6. */
                     | PORT_PCR_MUX(PORT2_PCR6_MUX_mux00)

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_18 (pin 57) is configured as P3_18 */
    PORT_SetPinMux(BOARD_INITGPIOPINS_RLY_IN_PORT, BOARD_INITGPIOPINS_RLY_IN_PIN, kPORT_MuxAlt0);

    PORT3->PCR[18] = ((PORT3->PCR[18] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitCMP0Pins:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '97', peripheral: CMP0, signal: 'IN, 2N', pin_signal: P1_4/WUU0_IN8/FREQME_CLK_IN0/LPSPI0_PCS3/LPUART2_RXD/CT1_MAT2/EZH_PIO0/ADC0_A20/CMP0_IN2, identifier: MC2_FAULT}
  - {pin_num: '90', peripheral: CMP2, signal: 'IN, 2P', pin_signal: P0_23/WUU0_IN5/LPUART0_CTS_B/CT_INP3/CT0_MAT1/EZH_PIO13/ADC0_A13/CMP2_IN2}
  - {pin_num: '25', peripheral: CMP1, signal: 'IN, 0P', pin_signal: P2_3/WUU0_IN19/TRIG_IN7/LPUART0_CTS_B/LPUART2_RXD/CT_INP13/CT2_MAT3/EZH_PIO27/ADC0_A3/CMP1_IN0/ADC1_A4}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitCMP0Pins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitCMP0Pins(void)
{
    /* PORT0: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT0);
    /* PORT1: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT1);
    /* PORT2: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT2);
    /* ADC0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kADC0_RST_SHIFT_RSTn);
    /* CMP2 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kCMP2_RST_SHIFT_RSTn);
    /* PORT0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT0_RST_SHIFT_RSTn);
    /* PORT1 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT1_RST_SHIFT_RSTn);
    /* ADC1 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kADC1_RST_SHIFT_RSTn);
    /* CMP1 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kCMP1_RST_SHIFT_RSTn);
    /* PORT2 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT2_RST_SHIFT_RSTn);

    /* PORT0_23 (pin 90) is configured as CMP2_IN2 */
    PORT_SetPinMux(BOARD_INITCMP0PINS_MC1_CUR_DCB_PORT, BOARD_INITCMP0PINS_MC1_CUR_DCB_PIN, kPORT_MuxAlt0);

    PORT0->PCR[23] = ((PORT0->PCR[23] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Disables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe0));

    /* PORT1_4 (pin 97) is configured as CMP0_IN2 */
    PORT_SetPinMux(BOARD_INITCMP0PINS_MC2_FAULT_PORT, BOARD_INITCMP0PINS_MC2_FAULT_PIN, kPORT_MuxAlt0);

    PORT1->PCR[4] = ((PORT1->PCR[4] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Disables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe0));

    /* PORT2_3 (pin 25) is configured as CMP1_IN0 */
    PORT_SetPinMux(BOARD_INITCMP0PINS_MC3_CUR_DCB_PORT, BOARD_INITCMP0PINS_MC3_CUR_DCB_PIN, kPORT_MuxAlt0);

    PORT2->PCR[3] = ((PORT2->PCR[3] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Disables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe0));
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitOPAMP0Pins:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '35', peripheral: OPAMP0, signal: 'op_inn, 0', pin_signal: P2_13/TRIG_IN8/LPSPI1_SDO/LPUART1_TXD/CT4_MAT1/CT0_MAT1/EZH_PIO17/CAN0_TXD/ADC1_A5/ADC3_A5/OPAMP0_INN}
  - {pin_num: '36', peripheral: OPAMP0, signal: OUT, pin_signal: P2_15/WUU0_IN21/TRIG_OUT4/LPSPI1_SDI/LPUART1_RTS_B/CT4_MAT3/CT0_MAT2/EZH_PIO18/OPAMP0_OUT/ADC0_A2}
  - {pin_num: '34', peripheral: OPAMP0, signal: 'op_inp, 0', pin_signal: P2_12/WUU0_IN20/LPSPI1_SCK/LPUART1_RXD/CT4_MAT0/CT0_MAT0/EZH_PIO16/CAN0_RXD/ADC0_A5/ADC2_A5/OPAMP0_INP}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitOPAMP0Pins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitOPAMP0Pins(void)
{
    /* PORT2: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT2);
    /* OPAMP0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kOPAMP0_RST_SHIFT_RSTn);
    /* PORT2 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT2_RST_SHIFT_RSTn);

    /* PORT2_12 (pin 34) is configured as OPAMP0_INP */
    PORT_SetPinMux(PORT2, 12U, kPORT_MuxAlt0);

    PORT2->PCR[12] = ((PORT2->PCR[12] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Disables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe0));

    /* PORT2_13 (pin 35) is configured as OPAMP0_INN */
    PORT_SetPinMux(PORT2, 13U, kPORT_MuxAlt0);

    PORT2->PCR[13] = ((PORT2->PCR[13] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Disables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe0));

    /* PORT2_15 (pin 36) is configured as OPAMP0_OUT */
    PORT_SetPinMux(PORT2, 15U, kPORT_MuxAlt0);

    PORT2->PCR[15] = ((PORT2->PCR[15] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Disables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe0));
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_SmartDMA0Pins:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '53', peripheral: GPIO3, signal: 'GPIO, 22', pin_signal: P3_22/LPUART1_RTS_B/CT_INP10/PWM1_X2/EZH_PIO22/ADC3_A20, identifier: MC3_BT, direction: OUTPUT}
  - {pin_num: '54', peripheral: GPIO3, signal: 'GPIO, 21', pin_signal: P3_21/TRIG_OUT1/LPI2C3_SCL/LPUART1_TXD/CT2_MAT3/PWM0_X3/PWM1_B3/EZH_PIO21/ADC3_A19, identifier: MC3_BB,
    direction: OUTPUT}
  - {pin_num: '55', peripheral: GPIO3, signal: 'GPIO, 20', pin_signal: P3_20/TRIG_OUT0/LPI2C3_SDA/LPUART1_RXD/CT2_MAT2/PWM0_X2/PWM1_A3/EZH_PIO20/ADC3_A18, direction: OUTPUT}
  - {pin_num: '56', peripheral: GPIO3, signal: 'GPIO, 19', pin_signal: P3_19/LPUART4_TXD/CT2_MAT1/PWM0_X1/PWM1_X1/EZH_PIO19, direction: OUTPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_SmartDMA0Pins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_SmartDMA0Pins(void)
{
    /* GPIO3: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GateGPIO3);
    /* PORT3: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT3);
    /* GPIO3 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kGPIO3_RST_SHIFT_RSTn);
    /* PORT3 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT3_RST_SHIFT_RSTn);

    gpio_pin_config_t MC3_CT_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO3_19 (pin 56)  */
    GPIO_PinInit(BOARD_SMARTDMA0PINS_MC3_CT_GPIO, BOARD_SMARTDMA0PINS_MC3_CT_PIN, &MC3_CT_config);

    gpio_pin_config_t MC3_CB_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO3_20 (pin 55)  */
    GPIO_PinInit(BOARD_SMARTDMA0PINS_MC3_CB_GPIO, BOARD_SMARTDMA0PINS_MC3_CB_PIN, &MC3_CB_config);

    gpio_pin_config_t MC3_BB_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO3_21 (pin 54)  */
    GPIO_PinInit(BOARD_SMARTDMA0PINS_MC3_BB_GPIO, BOARD_SMARTDMA0PINS_MC3_BB_PIN, &MC3_BB_config);

    gpio_pin_config_t MC3_BT_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO3_22 (pin 53)  */
    GPIO_PinInit(BOARD_SMARTDMA0PINS_MC3_BT_GPIO, BOARD_SMARTDMA0PINS_MC3_BT_PIN, &MC3_BT_config);

    /* PORT3_19 (pin 56) is configured as P3_19 */
    PORT_SetPinMux(BOARD_SMARTDMA0PINS_MC3_CT_PORT, BOARD_SMARTDMA0PINS_MC3_CT_PIN, kPORT_MuxAlt0);

    PORT3->PCR[19] = ((PORT3->PCR[19] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_20 (pin 55) is configured as P3_20 */
    PORT_SetPinMux(BOARD_SMARTDMA0PINS_MC3_CB_PORT, BOARD_SMARTDMA0PINS_MC3_CB_PIN, kPORT_MuxAlt0);

    PORT3->PCR[20] = ((PORT3->PCR[20] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_21 (pin 54) is configured as P3_21 */
    PORT_SetPinMux(BOARD_SMARTDMA0PINS_MC3_BB_PORT, BOARD_SMARTDMA0PINS_MC3_BB_PIN, kPORT_MuxAlt0);

    PORT3->PCR[21] = ((PORT3->PCR[21] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_22 (pin 53) is configured as P3_22 */
    PORT_SetPinMux(BOARD_SMARTDMA0PINS_MC3_BT_PORT, BOARD_SMARTDMA0PINS_MC3_BT_PIN, kPORT_MuxAlt0);

    PORT3->PCR[22] = ((PORT3->PCR[22] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_eQDC0Pins:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '40', peripheral: eQDC0, signal: PHASEA, pin_signal: P2_20/TRIG_IN8/LPSPI1_PCS2/CT2_MAT0/EZH_PIO22/ADC2_A6/OPAMP3_INP}
  - {pin_num: '41', peripheral: eQDC0, signal: PHASEB, pin_signal: P2_21/TRIG_IN9/LPSPI1_PCS3/CT2_MAT1/EZH_PIO23/ADC3_A6/OPAMP3_INN}
  - {pin_num: '48', peripheral: eQDC0, signal: INDEX, pin_signal: P3_31/LPTMR0_ALT2/TRIG_IN10/LPI2C3_SDAS/LPUART4_CTS_B/CT0_MAT3/PWM1_B0/EZH_PIO31/ADC1_A20, identifier: MC1_ENC_I}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_eQDC0Pins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_eQDC0Pins(void)
{
    /* INPUTMUX0: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GateINPUTMUX0);
    /* PORT2: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT2);
    /* PORT3: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT3);
    /* INPUTMUX0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kINPUTMUX0_RST_SHIFT_RSTn);
    /* PORT2 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT2_RST_SHIFT_RSTn);
    /* PORT3 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT3_RST_SHIFT_RSTn);
    /*  TrigIn10 connect to Qdc0Index 0 */
    INPUTMUX_AttachSignal(INPUTMUX0, 0U, kINPUTMUX_TrigIn10ToQdc0Index);
    /*  TrigIn8 connect to Qdc0Phasea 0 */
    INPUTMUX_AttachSignal(INPUTMUX0, 0U, kINPUTMUX_TrigIn8ToQdc0Phasea);
    /*  TrigIn9 connect to Qdc0Phaseb 0 */
    INPUTMUX_AttachSignal(INPUTMUX0, 0U, kINPUTMUX_TrigIn9ToQdc0Phaseb);

    PORT2->PCR[20] = ((PORT2->PCR[20] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                      /* Pin Multiplex Control: PORT2_20 (pin 40) is configured as TRIG_IN8. */
                      | PORT_PCR_MUX(PORT2_PCR20_MUX_mux01)

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    PORT2->PCR[21] = ((PORT2->PCR[21] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                      /* Pin Multiplex Control: PORT2_21 (pin 41) is configured as TRIG_IN9. */
                      | PORT_PCR_MUX(PORT2_PCR21_MUX_mux01)

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_31 (pin 48) is configured as TRIG_IN10 */
    PORT_SetPinMux(BOARD_EQDC0PINS_MC1_ENC_I_PORT, BOARD_EQDC0PINS_MC1_ENC_I_PIN, kPORT_MuxAlt1);

    PORT3->PCR[31] = ((PORT3->PCR[31] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_eQDC1Pins:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '20', peripheral: eQDC1, signal: PHASEA, pin_signal: P4_6/TRIG_IN4/LPI2C2_HREQ/LPUART3_CTS_B/CT_INP6/PWM0_A0/EZH_PIO26/ADC2_A22}
  - {pin_num: '21', peripheral: eQDC1, signal: PHASEB, pin_signal: P4_7/TRIG_IN5/LPUART3_RTS_B/CT_INP7/PWM0_B0/EZH_PIO27/ADC2_A23}
  - {pin_num: '22', peripheral: eQDC1, signal: INDEX, pin_signal: P2_0/WUU0_IN18/TRIG_IN6/LPUART0_RXD/LPUART4_CTS_B/CT_INP16/CT2_MAT0/EZH_PIO24/ADC0_A0/OPAMP2_INP}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_eQDC1Pins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_eQDC1Pins(void)
{
    /* INPUTMUX0: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GateINPUTMUX0);
    /* PORT2: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT2);
    /* PORT4: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT4);
    /* INPUTMUX0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kINPUTMUX0_RST_SHIFT_RSTn);
    /* PORT2 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT2_RST_SHIFT_RSTn);
    /* PORT4 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT4_RST_SHIFT_RSTn);
    /*  TrigIn6 connect to Qdc1Index 0 */
    INPUTMUX_AttachSignal(INPUTMUX0, 0U, kINPUTMUX_TrigIn6ToQdc1Index);
    /*  TrigIn4 connect to Qdc1Phasea 0 */
    INPUTMUX_AttachSignal(INPUTMUX0, 0U, kINPUTMUX_TrigIn4ToQdc1Phasea);
    /*  TrigIn5 connect to Qdc1Phaseb 0 */
    INPUTMUX_AttachSignal(INPUTMUX0, 0U, kINPUTMUX_TrigIn5ToQdc1Phaseb);

    /* PORT2_0 (pin 22) is configured as TRIG_IN6 */
    PORT_SetPinMux(PORT2, 0U, kPORT_MuxAlt1);

    PORT2->PCR[0] = ((PORT2->PCR[0] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    PORT4->PCR[6] = ((PORT4->PCR[6] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                     /* Pin Multiplex Control: PORT4_6 (pin 20) is configured as TRIG_IN4. */
                     | PORT_PCR_MUX(PORT4_PCR6_MUX_mux01)

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    PORT4->PCR[7] = ((PORT4->PCR[7] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                     /* Pin Multiplex Control: PORT4_7 (pin 21) is configured as TRIG_IN5. */
                     | PORT_PCR_MUX(PORT4_PCR7_MUX_mux01)

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitOPAMP1Pins:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '38', peripheral: OPAMP1, signal: 'op_inn, 0', pin_signal: P2_17/TRIG_IN9/LPSPI1_PCS0/LPUART1_CTS_B/CT3_MAT1/CT0_MAT3/EZH_PIO20/ADC1_A6/ADC3_A4/OPAMP1_INN}
  - {pin_num: '39', peripheral: OPAMP1, signal: OUT, pin_signal: P2_19/TRIG_OUT5/CT3_MAT3/EZH_PIO21/ADC1_A2/OPAMP1_OUT}
  - {pin_num: '37', peripheral: OPAMP1, signal: 'op_inp, 0', pin_signal: P2_16/LPSPI1_SDI/LPUART1_RTS_B/CT3_MAT0/CT0_MAT2/EZH_PIO19/ADC0_A6/ADC2_A4/OPAMP1_INP}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitOPAMP1Pins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitOPAMP1Pins(void)
{
    /* PORT2: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT2);
    /* PORT2 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT2_RST_SHIFT_RSTn);

    /* PORT2_16 (pin 37) is configured as OPAMP1_INP */
    PORT_SetPinMux(PORT2, 16U, kPORT_MuxAlt0);

    PORT2->PCR[16] = ((PORT2->PCR[16] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Disables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe0));

    PORT2->PCR[17] = ((PORT2->PCR[17] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                      /* Pin Multiplex Control: PORT2_17 (pin 38) is configured as OPAMP1_INN. */
                      | PORT_PCR_MUX(PORT2_PCR17_MUX_mux00)

                      /* Input Buffer Enable: Disables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe0));

    PORT2->PCR[19] = ((PORT2->PCR[19] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                      /* Pin Multiplex Control: PORT2_19 (pin 39) is configured as OPAMP1_OUT. */
                      | PORT_PCR_MUX(PORT2_PCR19_MUX_mux00)

                      /* Input Buffer Enable: Disables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe0));
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitDACPins:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '24', peripheral: DAC0, signal: OUT, pin_signal: P2_2/TRIG_IN6/LPUART0_RTS_B/LPUART2_TXD/CT_INP12/CT2_MAT2/EZH_PIO26/ADC0_A4/CMP0_IN0/DAC0_OUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitDACPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitDACPins(void)
{
    /* PORT2: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT2);
    /* DAC0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kDAC0_RST_SHIFT_RSTn);
    /* PORT2 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT2_RST_SHIFT_RSTn);

    PORT2->PCR[2] = ((PORT2->PCR[2] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                     /* Pin Multiplex Control: PORT2_2 (pin 24) is configured as DAC0_OUT. */
                     | PORT_PCR_MUX(PORT2_PCR2_MUX_mux00)

                     /* Input Buffer Enable: Disables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe0));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
